### ISSUE TITLE
Crashma server

### ISSUE THREAD

**Issue by TheButterbrotMan** [OhDricky/Illager-Expansion#3]
https://bytebin.lucko.me/L0Zbdii5wD

**Comment by Kuyuna** [comment]
[crash-2022-04-23_18.33.46-server.txt](https://github.com/OhDricky/Illager-Expansion/files/8548189/crash-2022-04-23_18.33.46-server.txt)

**Comment by OhDricky** [comment]
Should hopefully be fixed in the next update! See [this issue](https://github.com/OhDricky/Illager-Expansion/issues/2) for more info
